### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by geraldodev** [OvermindDL1/overbots#1]
both master and pt6 are showing
```
FAILED: src/tea_json.cmj /home/geraldo/overbots/node_modules/bucklescript-tea/lib/es6/src/tea_json.js src/tea_json.cmi
/home/geraldo/overbots/node_modules/bs-platform/bin/bsc.exe -bs-package-name bucklescript-tea  -bs-package-output es6:lib/es6/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I src  -nostdlib -I '/home/geraldo/overbots/node_modules/bs-platform/lib/ocaml' -bs-cross-module-opt -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o src/tea_json.mlast -c  src/tea_json.mlast
File "/home/geraldo/overbots/node_modules/bucklescript-tea/src/tea_json.ml", line 30, characters 16-26:
Error: Unbound value reify_type
Hint: Did you mean reifyType?
[8/16] Building src/tea_app.cmj /home/geraldo/overbots/node_modules/bucklescript-tea/lib/es6/src/tea_app.js src/tea_app.cmi
ninja: build stopped: subcommand failed.

```

**Comment by OvermindDL1** [comment]
Bucklescript 1.7.5 I think it was had an API breaking change without bumping the API version number to 2.0.0, so for now just have to downgrade Bucklescript to 1.7.4 or older until I update (which just involves bumping the bucklescript-tea version in the package.json as it is already updated, I'll leave this open until I do that too, maybe today).  :-)

I really hope Bucklescript follow Semver in the future as that is what NPM uses to verify compatibility.  ^.^;

**Comment by OvermindDL1** [comment]
Updated to latest Bucklescript and latest Tea (see commit log), grab master to update.  :-)
Closing.  :-)

Thanks much!!  I entirely forgot about this.  ^.^;

**Comment by geraldodev** [comment]
Thank you!

Updated from master, removed node_modules, issued npm install and npm run
build and got

```
1/10] Building src/tea_json.cmj
/home/geraldo/overbots/node_modules/bucklescript-tea/lib/es6/src/tea_json.js
src/tea_json.cmi
FAILED: src/tea_json.cmj
/home/geraldo/overbots/node_modules/bucklescript-tea/lib/es6/src/tea_json.js
src/tea_json.cmi
/home/geraldo/overbots/node_modules/bs-platform/bin/bsc.exe
-bs-package-name bucklescript-tea  -bs-package-output es6:lib/es6/src
-bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I src
-nostdlib -I '/home/geraldo/overbots/node_modules/bs-platform/lib/ocaml'
-bs-cross-module-opt -no-alias-deps -color always -w
-40+6+7+27+32..39+44+45 -o src/tea_json.mlast -c  src/tea_json.mlast
File "/home/geraldo/overbots/node_modules/bucklescript-tea/src/tea_json.ml",
line 30, characters 16-26:
Error: Unbound value reify_type
Hint: Did you mean reifyType?
[6/10] Building src/tea_html.cmj
/home/geraldo/overbots/node_modules/bucklescript-tea/lib/es6/src/tea_html.js
src/tea_html.cmi
ninja: build stopped: subcommand failed.
Failure: /home/geraldo/overbots/node_modules/bs-platform/bin/ninja.exe
 Location: /home/geraldo/overbots/node_modules/bucklescript-tea/lib/bs
Error happened when running command
/home/geraldo/overbots/node_modules/bs-platform/bin/bsb.exe with args [
'-make-world'
```

I'm using nodejs 8.1.1 and npm 5.0.3


2017-06-15 11:28 GMT-03:00 OvermindDL1 <notifications@github.com>:

**Comment by OvermindDL1** [comment]
What version of bucklescript-tea is installed (`grep version node_modules/bucklescript-tea/package.json`)?  This package requires at least 0.6.0 as per:  https://github.com/OvermindDL1/overbots/blob/master/package.json#L13
And what commit hash are you using on this project (`git rev-parse HEAD` should be `8621cbd3253ae6d87ccfda4ac2e32f164606fc96`)?

That error should only happen on older versions when using a newer bucklescript.  I just tested it here with a fresh `git clone` and it installed and compiled fine?
```shell
$ git clone git@github.com:OvermindDL1/overbots.git
Cloning into 'overbots'...
remote: Counting objects: 209, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 209 (delta 0), reused 5 (delta 0), pack-reused 189R
Receiving objects: 100% (209/209), 132.01 KiB | 0 bytes/s, done.
Resolving deltas: 100% (86/86), done.
Checking connectivity... done.

$ cd overbots
$ npm install && npm run build
... snip building

$ echo $?
0

**Comment by geraldodev** [comment]
0.5.1

Strange, I've removed node_modules...

2017-06-15 15:30 GMT-03:00 OvermindDL1 <notifications@github.com>:

**Comment by OvermindDL1** [comment]
> Strange, I've removed node_modules...

Are you sure your git is up to date with master then?  What does the overbots local package.json require for the tea version?  Are you on rev `8621cbd3253ae6d87ccfda4ac2e32f164606fc96` or newer?

**Comment by geraldodev** [comment]
Probably I have messed up something. I removed the project, cloned again
and it compiled. Thank You!

2017-06-15 16:22 GMT-03:00 OvermindDL1 <notifications@github.com>:
